### ISSUE TITLE
Failed to create gcp:apigateway:ApiConfig

### ISSUE THREAD

**Issue by 23ewrdtf** [pulumi/pulumi-gcp#1033]
### What happened?

**ERROR:**

When trying to create gcp:apigateway:ApiConfig I get below error:

```
✗  pulumi preview --verbose 4
Please choose a stack, or create a new one: dev
Previewing update (dev):
     Type                 Name      Plan     Info
     pulumi:pulumi:Stack  Vega-dev           7 messages


Diagnostics:
  pulumi:pulumi:Stack (Vega-dev):
    Error: gcp:apigateway/apiConfig:ApiConfig is not assignable from {api: string, apiConfigId: string, openapiDocuments: {document: {path: string, contents: string}}}
      on Pulumi.yaml line 24:
      24:         document:
      25:           path: "spec.yaml"
      26:           contents: "base64"
    Cannot assign '{api: string, apiConfigId: string, openapiDocuments: {document: {path: string, contents: string}}}' to 'gcp:apigateway/apiConfig:ApiConfig':
      openapiDocuments: Cannot assign '{document: {path: string, contents: string}}' to 'List<gcp:apigateway/ApiConfigOpenapiDocument:ApiConfigOpenapiDocument>'

Outputs:
  - pulumi-data-ukbucketName: "REDACTED"
  - pulumi-data-ukbucketUrl : "gs://REDACTED"
```

**Pulumi.yaml**

```
name: Vega
runtime: yaml
resources:
  pulumi-data-uk:
    type: gcp:storage:Bucket
    properties:
      location: EU
      uniformBucketLevelAccess: true
  pulumi-api-gw-api:
    type: gcp:apigateway:Api
    properties:
      apiId: api-gw-dev-id
  pulumi-api-gw-service-account:
    type: gcp:serviceAccount:Account
    properties:
      accountId: pulumi-api-gw-service-account
      displayName: pulumi-api-gw-service-account
  pulumi-api-gw-config:
    type: gcp:apigateway:ApiConfig
    properties:
      api: ${pulumi-api-gw-api.id}
      apiConfigId: pulumi-api-gw-config1
      openapiDocuments:
        document:
          path: "spec.yaml"
          contents: "base64"
outputs:
  pulumi-data-ukbucketName: ${pulumi-data-uk.name}
  pulumi-data-ukbucketUrl: ${pulumi-data-uk.url}
  pulumi-api-gw-apiId: ${pulumi-api-gw-api.id}
  pulumi-api-gw-apiName: ${pulumi-api-gw-api.name}
  pulumi-api-gw-configName: ${pulumi-api-gw-config.serviceConfigId}
  pulumi-api-gw-configId: ${pulumi-api-gw-config.serviceConfigId}
  pulumi-api-gw-configServiceConfigId: ${pulumi-api-gw-config.serviceConfigId}
```

### Expected Behavior

gcp:apigateway:ApiConfig should be created.

### Steps to reproduce

```
export GOOGLE_APPLICATION_CREDENTIALS=key.json
export PULUMI_CONFIG_PASSPHRASE=""
export GITHUB_TOKEN=${PULUMI_TOKEN_GITHUB}
pulumi login ${PULUMI_STATE_BUCKET}
pulumi stack select ${CI_COMMIT_BRANCH}
pulumi config set gcp:project REDACTED
pulumi config set gcp:region REDACTED
pulumi preview
```

### Output of `pulumi about`

Some private data has been REDACTED.

CLI          
Version      3.58.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME  VERSION
gcp   unknown
yaml  unknown

Host     
OS       darwin
Version  12.6.2
Arch     arm64

This project is written in yaml

Backend        
Name           REDACTED.local
URL            gs://REDACTED
User           REDACTED
Organizations  

No dependencies found

Pulumi locates its logs in /var/folders/REDACTED by default
warning: Failed to get information about the current stack: No current stack

### Additional context

Creation of `gcp:storage:Bucket`, `gcp:apigateway:Api`, `gcp:serviceAccount:Account` is successful.

The yaml example in docs is not being generated: https://github.com/pulumi/pulumi-gcp/issues/1030

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @23ewrdtf, since the type of `openapiDocuments` is [List<Property Map>](https://www.pulumi.com/registry/packages/gcp/api-docs/apigateway/apiconfig/#apiconfigopenapidocument), I believe the YAML list syntax is

```
      openapiDocuments:
        - document:
            path: "spec.yaml"
            contents: "base64"
```
