### ISSUE TITLE
Pulumi will replace a nodepool because of location change that doesn't change.

### ISSUE THREAD

**Issue by 23ewrdtf** [pulumi/pulumi-gcp#1117]
### What happened?

Hi, I have this block in `pulumi.yaml`. The `location` never change but when I run `pulumi preview` it always wants to replace the `nodepool` because of the `location` change. `Pulumi update` will replace the `nodepool`. It's in a loop for some reason.

```
gke-cluster-nodes:
    type: gcp:container:NodePool
    properties:
      cluster: ${gke-cluster.id}
      location: europe-west-2a
      nodeCount: 1
      nodeConfig:
        preemptible: true
        machineType: e2-medium
        serviceAccount: ${gke-cluster-nodepool-sa.email}
        oauthScopes:
          - https://www.googleapis.com/auth/cloud-platform
```

LOG:
```
$ pulumi preview
36Previewing update (stackname):
37@ previewing update....[resource plugin gcp-6.59.0] installing
38.
39    pulumi:pulumi:Stack stackname running 
40@ previewing update....
41.
42    gcp:serviceAccount:Account gke-cluster-sa  
43    gcp:compute:Network gke-cluster-vpc  
44    gcp:compute:Subnetwork gke-cluster-primary-range-services  
45    gcp:compute:Subnetwork gke-cluster-primary-range-nodes  
46    gcp:compute:Subnetwork gke-cluster-primary-range-pods  
47    gcp:container:Cluster gke-cluster  
48    gcp:serviceAccount:Account gke-cluster-nodepool-sa  
49 ++ gcp:container:NodePool gke-cluster-nodes create replacement [diff: ~location]
50 +- gcp:container:NodePool gke-cluster-nodes replace [diff: ~location]
51 -- gcp:container:NodePool gke-cluster-nodes delete original [diff: ~location]
52    pulumi:pulumi:Stack stackname  
53Resources:
54    +-1 to replace
55    8 unchanged
56warning: A new version of Pulumi is available. To upgrade from version '3.71.0' to '3.73.0', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
```

The reason I use 3.71.0' instead of '3.73.0 is that 3.73.0 is not available on Docker hub yet.

### Expected Behavior

`Pulumi preview` and `Pulumi update` should replace the `nodepool` as the location never changes.

### Steps to reproduce

Not sure. I can provide the full pulumi.yaml.

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.71.0
Go Version   go1.20.4
Go Compiler  gc
Plugins
NAME  VERSION
gcp   unknown
yaml  unknown
Host     
OS       debian
Version  11.7
Arch     x86_64
This project is written in yaml
No dependencies found
Pulumi locates its logs in /tmp by default
warning: A new version of Pulumi is available. To upgrade from version '3.71.0' to '3.73.0', visit https://pulumi.com/docs/install/ for manual instructions and release notes.

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@23ewrdtf thanks for reporting and sorry you're seeing this. Can you run this interactively and get the detailed diff; showing what the value is changing from and to?

In the meantime, I think you can fix this in your YAML program by adding `options.ignoreChanges`, like so:

```yaml
gke-cluster-nodes:
    type: gcp:container:NodePool
    properties:
      cluster: ${gke-cluster.id}
      location: europe-west-2a
      nodeCount: 1
      nodeConfig:
        preemptible: true
        machineType: e2-medium
        serviceAccount: ${gke-cluster-nodepool-sa.email}
        oauthScopes:
          - https://www.googleapis.com/auth/cloud-platform
    options:
      ignoreChanges:
        - location
```
