### ISSUE TITLE
warning: unable to detect a global setting for GCP project

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1236]
### What happened?

Getting a double warning on trying to do a `pulumi up` on a GCP project which otherwise succeeds:

```
Diagnostics:
  pulumi:pulumi:Stack (test-serviceaccount-test):
    warning: unable to detect a global setting for GCP Project;
    Pulumi will rely on per-resource settings for this operation.
    Set the GCP Project by using:
        `pulumi config set gcp:project <project>`
    warning: unable to detect a global setting for GCP Project;
    Pulumi will rely on per-resource settings for this operation.
    Set the GCP Project by using:
        `pulumi config set gcp:project <project>`
```

### Example

```
name: test

runtime:
  name: yaml

resources:

  provider:
    type: pulumi:providers:gcp
    options:
      version: 6.67.0

  tested-resource:
    type: gcp:serviceAccount:Account
    properties:
      accountId: sa${pulumi.stack}
      displayName: Test Service Account
      project: ${gcp:project}
    options:
      provider: ${provider}

```

```
pulumi config set gcp:project pulumi-development
pulumi up --yes
```

### Output of `pulumi about`

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  14.0
Arch     x86_64

This project is written in yaml

Current Stack: t0yv0/test/serviceaccount-test

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:serviceaccount-test::test::pulumi:pulumi:Stack::test-serviceaccount-test
pulumi:providers:gcp                urn:pulumi:serviceaccount-test::test::pulumi:providers:gcp::provider
gcp:serviceAccount/account:Account  urn:pulumi:serviceaccount-test::test::gcp:serviceAccount/account:Account::tested-resource


Found no pending operations associated with serviceaccount-test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
