### ISSUE TITLE
Deletion protection instructions confusing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1253]
### What happened?

Multiple resources in this provider here have a deletionProtection flag that by default locks them in and prevents them from being deleted. When you want to delete such a resource, you need to set the `deletionProtection` flag on it first. However the UX is very confusing on this since the instructions mention TF, not Pulumi, and are not cleanly actionable:

Similar issue:  https://github.com/pulumi/pulumi-gcp/issues/1209

One of the top-most resources is  gcp:bigquery:Table, deleting this resource shows:

```
Diagnostics:
  gcp:bigquery:Table (tested-resource):
    error: deleting urn:pulumi:serviceaccount-test::test::gcp:bigquery/table:Table::tested-resource: 1 error occurred:
        * cannot destroy instance without setting deletion_protection=false and running `terraform apply`

  pulumi:pulumi:Stack (test-serviceaccount-test):
    error: update failed
```

### Example

```
name: test
runtime:
    name: yaml
resources:
    provider:
        type: pulumi:providers:gcp
        options:
            version: 6.67.0
        properties:
            project: ${gcp:project}
    tested-resource:
        type: gcp:bigquery:Table
        options:
            provider: ${provider}
        properties:
            datasetId: ${defaultDataset.datasetId}
            # deletionProtection: false # TOGGLE THIS
            tableId: sheet      
    defaultDataset:
        type: gcp:bigquery:Dataset      
        options:
            provider: ${provider}
        properties:
            datasetId:
              fn::invoke:
                function: str:replace
                arguments:
                  old: "-"
                  new: ""
                  string: ds-${pulumi.stack}
                return: result
            defaultTableExpirationMs: 3.6e+06
            description: This is a test description
            friendlyName: test
            labels:
                env: default
            location: EU
```

### Output of `pulumi about`

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  14.0
Arch     x86_64

This project is written in yaml

Current Stack: t0yv0/test/serviceaccount-test

TYPE                          URN
pulumi:pulumi:Stack           urn:pulumi:serviceaccount-test::test::pulumi:pulumi:Stack::test-serviceaccount-test
pulumi:providers:str          urn:pulumi:serviceaccount-test::test::pulumi:providers:str::default
pulumi:providers:gcp          urn:pulumi:serviceaccount-test::test::pulumi:providers:gcp::provider
gcp:bigquery/dataset:Dataset  urn:pulumi:serviceaccount-test::test::gcp:bigquery/dataset:Dataset::defaultDataset
gcp:bigquery/table:Table      urn:pulumi:serviceaccount-test::test::gcp:bigquery/table:Table::tested-resource


Found no pending operations associated with serviceaccount-test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
