### ISSUE TITLE
Network name does not match regex

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1254]
### What happened?

Autonaming generates invalid name suggestions so network resource does not provision.

```
Diagnostics:
  gcp:compute:Network (defaultNetwork):
    error: gcp:compute/network:Network resource 'defaultNetwork' has a problem: "name" ("defaultNetwork-0d89d67") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$". Examine values at 'defaultNetwork.name'.
```

### Example

```
name: test
resources:
    defaultNetwork:
        options:
            provider: ${provider}
        type: gcp:compute:Network
    provider:
        options:
            version: 6.67.0
        properties:
            project: ${gcp:project}
        type: pulumi:providers:gcp
runtime:
    name: yaml
```

### Output of `pulumi about`

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  14.0
Arch     x86_64

This project is written in yaml

Current Stack: t0yv0/test/test-gcp-firewall

Found no resources associated with test-gcp-firewall

Found no pending operations associated with test-gcp-firewall

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
