### ISSUE TITLE
GCP bucket gets updated everytime after going from version 6.X to 7.x

### ISSUE THREAD

**Issue by fbarrerafalabella** [pulumi/pulumi-gcp#1378]
### What happened?

I updated the pulumi-gcp package to 7.2.1 from 6.55.1 and now everytime I perform a pulumi up it detects it needs to update the bucket component, but when getting the details, no change is shown, I wonder if on other projects this will result on pulumi trying to re-create the component

### Example

```
Previewing update (staging):
     Type                   Name                 Plan       Info
     pulumi:pulumi:Stack    api-gateway-staging             2 messages
 ~   └─ gcp:storage:Bucket  api-gateway          update

Diagnostics:
  pulumi:pulumi:Stack (api-gateway-staging):
    (node:50494) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)

Resources:
    ~ 1 to update
    59 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::api-gateway::pulumi:pulumi:Stack::api-gateway-staging]
    ~ gcp:storage/bucket:Bucket: (update) 🔒
        [id=api-gateway-47d88fc]
        [urn=urn:pulumi:staging::api-gateway::gcp:storage/bucket:Bucket::api-gateway]
        [provider=urn:pulumi:staging::api-gateway::pulumi:providers:gcp::default_7_2_1::a04f4d95-7ec2-47ea-9cc9-4bce938b4b76]
        forceDestroy: false
        location    : "US"
        name        : "api-gateway-47d88fc"
        storageClass: "STANDARD"
        versioning  : {
            enabled   : true
        }
```

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  14.1.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v21.1.0'

Backend
Name           MacBook-Pro-de-soporte-3.local
URL            gs://linio-support-pulumi-state
User           fernando.barrera
Organizations
Token type     personal

Pulumi locates its logs in /var/folders/wp/6_z83s8d3y93lr__9qm9_3jh0000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/fernando.barrera/Documents/GitHub/falabella/linio-infrastructure/applications/api-gateway/yarn.lock or /Users/fernando.barrera/Documents/GitHub/falabella/linio-infrastructure/applications/api-gateway/package-lock.json
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @fbarrerafalabella. I'm sorry to hear that. Can you please include some code that reproduces your issue. I tried with this program:

```yaml
name: dev-yaml
runtime: yaml
resources:
  gcp:
    type: pulumi:providers:gcp
    options:
      # version: 6.55.1 # <- start here, run `pulumi up`, then move to `7.2.1`.
      version: 7.2.1
    defaultProvider: true
  bucket:
    type: gcp:storage:Bucket
    properties:
      location: us-west1
      name: example-140879
      project: ${gcp_project}
      publicAccessPrevention: enforced
      uniformBucketLevelAccess: true
```

☝️ diffs cleanly after upgrading. Can you please include code that reproduces this issue? It might be what fields you have set on the bucket.
