### ISSUE TITLE
AutoNaming on gcpNetwork does not pass validators

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1576]
### What happened?

The default name selected for the Network resource cannot provision.

```
            gcp:compute:Network exampleNetwork  error: gcp:compute/network:Network resource 'exampleNetwork' has a problem: "name" ("exampleNetwork-12fde8d") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$". Examine values at 'exampleNetwork.name'.
         +  pulumi:pulumi:Stack network-test created (1s) 
            gcp:compute:Network exampleNetwork **failed** 1 error
        Diagnostics:
          gcp:compute:Network (exampleNetwork):
            error: gcp:compute/network:Network resource 'exampleNetwork' has a problem: "name" ("exampleNetwork-12fde8d") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$". Examine values at 'exampleNetwork.name'.
        
```

### Example

```
description: A minimal Google Cloud Pulumi YAML program
resources:
  exampleNetwork:
    type: gcp:compute/network:Network
    properties:
      autoCreateSubnetworks: false  # We'll create our own subnetwork

  exampleSubnetwork:
    type: gcp:compute/subnetwork:Subnetwork
    properties:
      name: pulumi-subnetwork
      network: ${exampleNetwork.id}
      ipCidrRange: "10.2.0.0/16"
      region: us-central1

  exampleRouter:
    type: gcp:compute/router:Router
    properties:
      name: pulumi-router
      network: ${exampleNetwork.id}
      region: us-central1
      bgp:
        asn: 64514
```

### Output of `pulumi about`

gcp         resource   7.7.0    208 MB  2 hours ago   2 hours ago

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
