### ISSUE TITLE
"Error 400: Must specify a field to update" When setting `deletionProtection` for gcp:container/cluster:Cluster

### ISSUE THREAD

**Issue by rustielin** [pulumi/pulumi-gcp#1688]
### What happened?

`pulumi up` (and also `pulumi up --refresh`) fails on a stack where the diff looks like this:

```
    ~ gcp:container/cluster:Cluster: (update)
...
      + deletionProtection     : true
```

`deletionProtection` was previously unset.

The error looks like this: a 400 from GCP. From the looks of it, it might be an issue with the underlying Terraform provider.

```
  gcp:container:Cluster:
    error: 1 error occurred:
        * googleapi: Error 400: Must specify a field to update.
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "0x98e3e8d4693d6371"
      }
    ]
    , badRequest
```

### Example

This happened after upgrading pulumi providers, though the diff in the `pulumi preview` no longer shows the provider diff. Migrated from `^6.67.0` to `^7.5.0` (7.7.0 now). Unsure if this is related

1. Create a GKE cluster at a previous verison of the GCP provider, not setting `deletionProtection`
2. Upgrade the version
3. See the default `deletionProtection = true` come in
4. Error 400

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.72.1
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/rustielin/Library/Caches/fnm_multishells/86986_1708454990685/bin/node' version='v18.16.1'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/rustielin
User           rustielin
Organizations  rustielin, aptos-labs
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @rustielin. Thanks for letting us know about this.

**Comment by rustielin** [comment]
Hey @iwahbe, is there any update on this?

**Comment by iwahbe** [comment]
We haven't had a chance to get to it yet. I'll try to take a look later this week.

**Comment by iwahbe** [comment]
Hey @rustielin. I took a look here and was unable to repro. I tried with this program:

```yaml
name: dev-yaml
runtime: yaml
resources:
  service:
    type: gcp:container/cluster:Cluster
    properties:
      location: us-central1
      initialNodeCount: 1
    options:
      # version: 7.15.0
      version: v6.67.0 # Comment out and uncomment ☝️ to upgrade
```

Everything worked fine. I never saw a diff for `deletionProtection`. 

Can you post a program that reproduces this error?
