### ISSUE TITLE
OIDC Access Token stored in state even if using env variable - results in expired credentials when destroying after expiry

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-gcp#1759]
### What happened?

I have an ESC environment set up for GCP OIDC named `gcp-access`
```
values:
  gcp:
    projectName: myProject
    login:
      fn::open::gcp-login:
        project: 1234456789
        oidc:
          workloadPoolId: myPoolId
          providerId: pulumi-cloud-pequod-oidc
          serviceAccount: myserviceaccount@serviceaccount.iam.gserviceaccount.com
          tokenLifetime: "1h"
  environmentVariables:
    GOOGLE_PROJECT: ${gcp.login.project}
    GOOGLE_OAUTH_ACCESS_TOKEN: ${gcp.login.accessToken}
```

I have a project with a `Pulumi.dev.yaml` file that looks like this:
```
environment:
  - gcp-access
```

I run `pulumi up` for a gcp program (`pulumi new gcp-typescript` is a good example to use).

Running `pulumi stack export` or looking at the provider in the Pulumi Cloud UI will show the accessToken is stored in state.

This causes problems when later, after the temporary token has expired, trying to destroy the stack will fail due to expired credentials.

### Example

See above

### Output of `pulumi about`

CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
gcp     7.11.2
nodejs  unknown

Host     
OS       darwin
Version  13.6.3
Arch     x86_64

This project is written in nodejs

Current Stack: dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::gcp-simple-test::pulumi:pulumi:Stack::gcp-simple-test-dev
pulumi:providers:gcp       urn:pulumi:dev::gcp-simple-test::pulumi:providers:gcp::default_7_11_2
gcp:storage/bucket:Bucket  urn:pulumi:dev::gcp-simple-test::gcp:storage/bucket:Bucket::my-bucket2

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME            VERSION
@pulumi/gcp     v7.11.2
@pulumi/pulumi  3.107.0
@types/node     18.19.21

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
