### ISSUE TITLE
Unable to create CloudRun service with Direct VPC egress

### ISSUE THREAD

**Issue by aver-generics** [pulumi/pulumi-gcp#1770]
### What happened?

I'm trying to create a CloudRun service with direct VPC egress enabled, but I'm getting the following error:

```
gcp:cloudrunv2:Service (my-service):
    error: gcp:cloudrunv2/service:Service resource 'my-service' has a problem: Invalid or unknown key. Examine values at 'my-service.template.vpcAccess.networkInterfaces'.
```

### Example

```
package main

import (
  "github.com/pulumi/pulumi-gcp/sdk/v7/go/gcp/cloudrunv2"
)

service, err := cloudrunv2.NewService(ctx, "my-service", &cloudrunv2.ServiceArgs{
  // ...
  Template: &cloudrunv2.ServiceTemplateArgs{
    // ...
    VpcAccess: &cloudrunv2.ServiceTemplateVpcAccessArgs{
        NetworkInterfaces: cloudrunv2.ServiceTemplateVpcAccessNetworkInterfaceArray{
             &cloudrunv2.ServiceTemplateVpcAccessNetworkInterfaceArgs{
                  Network:    pulumi.String("my-network-id"),
                  Subnetwork: pulumi.String("my-subnet-id"),
             },
         },
         Egress: pulumi.String("PRIVATE_RANGES_ONLY"),
     }
   }
}
```

### Output of `pulumi about`

```
CLI
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.22.0 darwin/arm64'
```

### Additional context

When running `pulumi about` I'm getting this warning:

```
warning: Failed to get information about the Pulumi program's dependencies: load go.mod:
...
```

These are the versions from my `go.mod` file:

```
github.com/pulumi/pulumi-docker/sdk/v4 v4.5.1
github.com/pulumi/pulumi-gcp/sdk/v7 v7.11.2
github.com/pulumi/pulumi/sdk/v3 v3.108.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@aver-generics Thanks for reporting this issue. 

For the `pulumi about` failure, can you show the output of running `go list -m -f {{.GoMod}}` in your pulumi project's directory?

**Comment by aver-generics** [comment]
Hi @iwahbe, sure, here is the output:

```
{project root dir}/apiserver/go.mod
{project root dir}/cli/go.mod
{project root dir}/core/go.mod
{project root dir}/db/migrations/go.mod
{project root dir}/db/migrations_base/go.mod
{project root dir}/iac/api/go.mod
{project root dir}/iac/db/go.mod
{project root dir}/iac/migrator/go.mod
{project root dir}/iac/network/go.mod
{project root dir}/iac/secrets/go.mod
{project root dir}/iac/storage/go.mod
```

I ran the command from within `{project root dir}/iac/api`.

**Comment by aver-generics** [comment]
Hi @iwahbe, any updates on this?

**Comment by iwahbe** [comment]
No updates yet. We will get around to this as soon as we are able.

**Comment by VenelinMartinov** [comment]
Hi @aver-generics, I tried the program above with both GCP 7.11.2 (your reported version) and gcp 7.14.0 (latest). The program runs successfully, so I have not been able to repro your issue. Do you have any additional information about it which might help use repro? It's really difficult to take any action here if we can't reproduce the problem.

**Comment by VenelinMartinov** [comment]
I have the following full program based on the user-reported one:
```golang
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v7/go/gcp/cloudrunv2"
	"github.com/pulumi/pulumi-gcp/sdk/v7/go/gcp/compute"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		network, err := compute.NewNetwork(ctx, "network", &compute.NetworkArgs{})
		if err != nil {
			return err
		}

		// Create a GCP subnetwork
		subnet, err := compute.NewSubnetwork(ctx, "subnetwork", &compute.SubnetworkArgs{
			Network:   network.ID(),
			IpCidrRange:   pulumi.String("10.10.0.0/16"),
			Region: pulumi.String("us-west1"),
		})
		
		if err != nil {
			return err
		}

		_, err = cloudrunv2.NewService(ctx, "my-service", &cloudrunv2.ServiceArgs{
			// ...
			Template: &cloudrunv2.ServiceTemplateArgs{
				// ...
				VpcAccess: &cloudrunv2.ServiceTemplateVpcAccessArgs{
					NetworkInterfaces: cloudrunv2.ServiceTemplateVpcAccessNetworkInterfaceArray{
						&cloudrunv2.ServiceTemplateVpcAccessNetworkInterfaceArgs{
							Network:    network.ID(),
							Subnetwork: subnet.ID(),
						},
					},
					Egress: pulumi.String("PRIVATE_RANGES_ONLY"),
				},
				Containers: &cloudrunv2.ServiceTemplateContainerArray{
					&cloudrunv2.ServiceTemplateContainerArgs{
						Image: pulumi.String("us-docker.pkg.dev/cloudrun/container/hello"),
                    },
				},
			},
			Location: pulumi.String("us-west1"),
			LaunchStage: pulumi.String("BETA"),
		},
		)
		if err!= nil {
            return err
        }
		return nil
	})
}
```

This runs fine.

I also tried in YAML

```YAML
name: gcp_cloudrun_yaml
runtime: yaml
resources:
  prov:
    type: pulumi:providers:gcp
    defaultProvider: true
    options:
      version: 7.14.0
  myNetwork: 
    type: gcp:compute:Network
    properties:
      autoCreateSubnetworks: false
  mySubnet:
    type: gcp:compute:Subnetwork
    properties:
      name: my-subnet-3
      region: 'us-central1' # Replace with your preferred region
      network: '${myNetwork.selfLink}'  # Link to the created network
      ipCidrRange: '10.128.0.0/20'
  myCloudRunService:
    type: gcp:cloudrunv2:Service
    properties:
      name: "my-service-2"
      location: 'us-central1' # Replace with your preferred location
      launchStage: BETA
      template:
        vpcAccess:
          egress: ALL_TRAFFIC
          networkInterfaces:
            - network: "${myNetwork.id}"
              subnetwork: "${mySubnet.id}"
        containers:
          - image: 'gcr.io/cloudrun/hello'
```

Which also seems fine.

@aver-generics do you have any suggestions on how to reproduce the issue? I have not been able to hit it. Perhaps you could supply us with a full program which exhibits the problem? That'd be much appreciated as it's very difficult to take any action here without a repro!
