### ISSUE TITLE
Document GCP auth with environment variables

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#1815]
### What happened?

https://www.pulumi.com/registry/packages/gcp/installation-configuration/ has nothing on using GOOGLE_OAUTH_ACCESS_TOKEN for authentication. This seems to have caused some confusion on how OIDC can be configured: https://github.com/pulumi/pulumi-gcp/issues/1693

We support authenticating via the GOOGLE_OAUTH_ACCESS_TOKEN env var, so we should have it documented.

### Example

the following ESC config should work - this avoids saving the token in the state

```
values:
  gcp:
    login:
      fn::open::gcp-login:
        project: -
        oidc:
          workloadPoolId:-
          providerId: -
          serviceAccount: -
  environmentVariables:
    GOOGLE_PROJECT: PROJECT
    GOOGLE_OAUTH_ACCESS_TOKEN: TOKEN
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
