### ISSUE TITLE
Failed to finish publishing

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-gcp#1831]
It was pointed out that we are missing the `sdk/v7.14.0` tag, which was caused by https://github.com/pulumi/pulumi-gcp/actions/runs/8270919591 failing.

We need to fix the release and ideally root cause why we were not alerted to the partial failure to publish.

**Comment by ringods** [comment]
@iwahbe your culprit:

https://github.com/pulumi/pulumi-package-publisher/blob/v0.0.14/lang/java/action.yml#L31

**Comment by t0yv0** [comment]
It appears that retrying the failing step has fixed the release, sdk/v7.14.0 has now been tagged.

**Comment by t0yv0** [comment]
Noticing that all the other steps use a different notification code:

```
    - if: failure() && github.event_name == 'push'
      name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        author_name: Failure in running ${{ matrix.language }} tests
        fields: repo,commit,author,action
        status: ${{ job.status }}
```
