### ISSUE TITLE
Auto naming does not work for gcp cloudrun Service

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#2162]
### Describe what happened

Auto naming yields an invalid name for the resource:

```
Diagnostics:
  pulumi:pulumi:Stack (gcp_2155_repro-dev):
    error: update failed

  gcp:cloudrun:Service (cloudrunService):
    error: 1 error occurred:
    	* Error creating Service: googleapi: Error 400: service.metadata.name: only lowercase, digits, and hyphens; must begin with letter, and may not end with hyphen; must be less than 64 characters.
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "only lowercase, digits, and hyphens; must begin with letter, and may not end with hyphen; must be less than 64 characters.",
            "field": "service.metadata.name"
          }
        ]
      }
    ]
```

### Sample program

```yaml
name: gcp_2155_repro
runtime: yaml
resources:
  cloudrunService:
    type: gcp:cloudrun/service:Service
    properties:
      name: gcp-2155-repro
      location: us-central1
      template:
        spec:
          containers:
            - image: gcr.io/cloudrun/hello


```

### Log output

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
