### ISSUE TITLE
Firestore database auto-naming incorrect

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#2183]
### Describe what happened

Firestore databases need all-lowercase names but we sometimes auto-name them with upper-case letters.

see also https://github.com/pulumi/pulumi-gcp/issues/2164

### Sample program

```yaml
name: firestore-field
runtime: yaml
config:
  gcpProj: string
resources:
  myFirestoreDatabase:
    type: gcp:firestore:Database
    properties:
      type: "FIRESTORE_NATIVE"
      project: ${gcpProj}
      locationId: "us-central"
```

### Log output

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
