### ISSUE TITLE
VPC Flow Logs are not available

### ISSUE THREAD

**Issue by lukasamd** [pulumi/pulumi-gcp#2993]
### Describe what happened

Hello,
I would like to automate VPC flow logs for subnetwork, but right now it's not possible

We can define log configuration using `logConfig` input, but after subnetwork creation, I still need to enable flow logs manually for it

It's because `gcp:compute:Subnetwork` does not support `enableFlowLogs` flag

This flag is supported in google-native provider only:
https://www.pulumi.com/registry/packages/google-native/api-docs/compute/v1/subnetwork/#enableflowlogs_yaml

It will be nice to add support for this flag if possible - some control tools required VPC logs to be enabled for all subnetworks

### Sample program

```
test-subnetwork-with-vpc-flow-logs:
  type: gcp:compute:Subnetwork
  properties:
    name: test-subnetwork-with-vpc-flow-logs
    project: my-test-project
    ipCidrRange: some-test-range
    region: us-central1
    network: some-test-network
    privateIpGoogleAccess: true
    logConfig:
      aggregationInterval: INTERVAL_1_MIN
      flowSampling: 0.5
      metadata: INCLUDE_ALL_METADATA
```

### Output of `pulumi about`

CLI
Version      3.147.0
Go Version   go1.23.5
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  gcp   7.21.2
language  yaml  1.13.0

Host
OS       debian
Version  12.9
Arch     x86_64

This project is written in yaml

Current Stack: infrastructure

TYPE                                                            URN
pulumi:pulumi:Stack                                             urn:pulumi:infrastructure::gcloud::pulumi:pulumi:Stack::gcloud-infrastructure
pulumi:providers:gcp                                            urn:pulumi:infrastructure::gcloud::pulumi:providers:gcp::gcp-provider
pulumi:providers:gcp                                            urn:pulumi:infrastructure::gcloud::pulumi:providers:gcp::gcp-provider-v7-21-2
// just some example

Found no pending operations associated with infrastructure

Backend
Name           LT-X16
URL            gs://ingenious-pulumi/gcloud
User           icon
Organizations
Token type     personal

Dependencies:
NAME  VERSION
gcp   7.21.2

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
