### ISSUE TITLE
`gcp.secretmanager.Secret`: `secretId` should be optional and autonamed

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-gcp#3180]
# Short Version

The `secretId` property of `gcp.secretmanager.Secret` should be autonamed. It's currently required.

# Long Version

Given the following custom autonaming in `Pulumi.yaml`

```yaml
config:
  pulumi:autonaming:
    value:
      pattern: ${project}-${stack}-${name}-${alphanum(4)}
```

And this program:

```python
import pulumi_gcp as gcp
import pulumi_aws as aws

gcp.secretmanager.Secret(
    "my-secret",
    secret_id="my-secret-id",
    replication={
        "auto": {}
    }
)

aws.secretsmanager.Secret(
    "my-secret",
)
```

The GCP version will not have any noticeable effect from autonaming, but the AWS secret will have the autonaming pattern applied.

Filed this as a blank issue since the bug/enhancement decision isn't clear for me in this case.
