### ISSUE TITLE
Always getting linkedResource as a diff for gcp:bigqueryanalyticshub:ListingSubscription whenever I run pulumi up

### ISSUE THREAD

**Issue by Dhanwant2134** [pulumi/pulumi-gcp#3188]
### Describe what happened

I created ListingSubscription using pulumi. Whenever I try to run pulumi up, it shows linkedResource as a diff `+ linkedResources: <null> `and then the update fails with the error `doesn't support update`

### Sample program

```python
listing_subscription = gcp.bigqueryanalyticshub.ListingSubscription("subscription",
location="US",
data_exchange_id=exchange.data_exchange_id,
listing_id=listing.listing_id,
project=subscription_dataset.project,
destination_dataset={
"location": "US",
"dataset_reference": {
"dataset_id": destination_dataset,
"project_id": destination_project
},
})
```

### Output of `pulumi about`

NAME VERSION
google-cloud-bigquery-data-exchange 0.5.19
grpcio-status 1.72.0
pulumi_gcp 8.27.0
pulumi-google-native 0.32.0
setuptools 65.5.0
virtualenv 20.25.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @Dhanwant2134, thank you for this issue and apologies for the difficulties you're having.

Could you please update the issue with the complete console output of `pulumi up` including error?

To let us help you as soon as possible, could you please provide us with a complete sample program we can run on our end that reproduces this bug?

This is almost certainly an upstream issue around defaults, but I didn't find a related issue. We'll take a look as soon as we can.

**Comment by VenelinMartinov** [comment]
Failed to repro this with the following program:

<details>

```yaml
name: gcp_3188
runtime: yaml

variables: {}
resources:
  subscriptionDataset:
    type: gcp:bigquery:Dataset
    properties:
      datasetId: my_listing
      friendlyName: my_listing
      description: ""
      location: US
  subscription:
    type: gcp:bigqueryanalyticshub:DataExchange
    properties:
      location: US
      dataExchangeId: my_data_exchange
      displayName: my_data_exchange
      description: ""
  subscriptionListing:
    type: gcp:bigqueryanalyticshub:Listing
    properties:
      location: US
      dataExchangeId: ${subscription.dataExchangeId}
      listingId: my_listing
      displayName: my_listing
      description: ""
      bigqueryDataset:
        dataset: ${subscriptionDataset.id}
  subscriptionListingSubscription:
    type: gcp:bigqueryanalyticshub:ListingSubscription
    properties:
      location: US
      dataExchangeId: ${subscription.dataExchangeId}
      listingId: ${subscriptionListing.listingId}
      destinationDataset:
        description: A test subscription
        friendlyName: "\U0001F44B"
        labels:
          testing: '123'
        location: US
        datasetReference:
          datasetId: destination_dataset
          projectId: ${subscriptionDataset.project}


```

</details>


```
pulumi preview --diff
Previewing update (dev)

View Live: https://app.pulumi.com/pulumi/gcp_3188/dev/previews/08a4b48f-6ab9-4690-8216-1200c361b28b

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::gcp_3188::pulumi:pulumi:Stack::gcp_3188-dev]
Resources:              
    5 unchanged
```

@Dhanwant2134 was this error a result of upgrading the provider perhaps? If so, can you please let us know which version you upgraded from?

If not, were there any other changes to the resource?
