### ISSUE TITLE
cloud run: typescript pulumi missing timeoutSeconds parameter

### ISSUE THREAD

**Issue by ernestas-poskus** [pulumi/pulumi-gcp#354]
Spec example from cloud run YAML section should contain `timeoutSeconds` parameter. 

```yaml
spec:
  traffic:
  - percent: 100
    latestRevision: true
  template:
    metadata:
      name: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        autoscaling.knative.dev/maxScale: '9'
    spec:
      timeoutSeconds: 4
      serviceAccountName: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      containerConcurrency: 30
      containers:
      - image: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ports:
        - containerPort: 8080
        env:
```

![Screenshot from 2020-05-24 21-12-21](https://user-images.githubusercontent.com/4499780/82815829-a0ed0580-9ea2-11ea-95cb-4288df37e84e.png)

```typescript
    interface ServiceTemplateSpec {
        /**
         * ContainerConcurrency specifies the maximum allowed in-flight (concurrent)
         * requests per container of the Revision. Values are:
         * - `0` thread-safe, the system should manage the max concurrency. This is
         * the default value.
         * - `1` not-thread-safe. Single concurrency
         * - `2-N` thread-safe, max concurrency of N
         */
        containerConcurrency?: pulumi.Input<number>;
        /**
         * Container defines the unit of execution for this Revision.
         * In the context of a Revision, we disallow a number of the fields of
         * this Container, including: name, ports, and volumeMounts.
         * The runtime contract is documented here:
         * https://github.com/knative/serving/blob/master/docs/runtime-contract.md  Structure is documented below.
         */
        containers?: pulumi.Input<pulumi.Input<inputs.cloudrun.ServiceTemplateSpecContainer>[]>;
        /**
         * Email address of the IAM service account associated with the revision of the
         * service. The service account represents the identity of the running revision,
         * and determines what permissions the revision has. If not provided, the revision
         * will use the project's default service account.
         */
        serviceAccountName?: pulumi.Input<string>;
        /**
         * -
         * ServingState holds a value describing the state the resources
         * are in for this Revision.
         * It is expected
         * that the system will manipulate this based on routability and load.
         */
        servingState?: pulumi.Input<string>;
    }

```
