### ISSUE TITLE
CloudSQL - Query Insights configuration is missing

### ISSUE THREAD

**Issue by DStoyanoff** [pulumi/pulumi-gcp#523]
Hello Pulumi,
First of all, I would like to congratulate the grate job you did with Pulumi. I am so far enjoying it very much.

Playing with CloudSQL configurations in the Google Console, I have discovered there is the [Query Insights](https://cloud.google.com/sql/docs/postgres/insights-overview?_ga=2.233161436.-352427718.1608540838) functionality that can show you detailed durations of the queries by client/application and etc.

This configuration however does not exist in the TypeScript/DotNet SDK.

Here is a description of the available config in instance.settings:
```
insightsConfig: {
  queryInsightsEnabled: true,
  queryStringLength: 1024,
  recordApplicationTags: true,
  recordClientAddress: true,
},
```

Also, here is the result of `gcloud  sql instances describe` when the Query Insights is enabled from the Google Console:
```
backendType: SECOND_GEN
connectionName: **
databaseVersion: POSTGRES_12
etag: 2dd7c48007e3ccf7a3ef3d43f97034b38e7096f451caf53dfb3dac9ade5ae77f
gceZone: europe-west1-d
instanceType: CLOUD_SQL_INSTANCE
ipAddresses:
- ipAddress: **
  type: PRIMARY
kind: sql#instance
name: **
project: **
region: europe-west1
selfLink: **
serverCaCert: **
serviceAccountEmailAddress: **
settings:
  activationPolicy: ALWAYS
  availabilityType: ZONAL
  backupConfiguration:
    backupRetentionSettings:
      retainedBackups: 7
      retentionUnit: COUNT
    enabled: false
    kind: sql#backupConfiguration
    location: eu
    pointInTimeRecoveryEnabled: false
    replicationLogArchivingEnabled: false
    startTime: 05:00
    transactionLogRetentionDays: 7
  dataDiskSizeGb: '10'
  dataDiskType: PD_SSD
  insightsConfig:
    queryInsightsEnabled: true
    queryStringLength: 1024
    recordApplicationTags: true
    recordClientAddress: true
  ipConfiguration:
    authorizedNetworks:
    - kind: sql#aclEntry
      name: ''
      value: 0.0.0.0/0
    ipv4Enabled: true
    requireSsl: false
  kind: sql#settings
  locationPreference:
    kind: sql#locationPreference
    zone: europe-west1-d
  maintenanceWindow:
    day: 0
    hour: 0
    kind: sql#maintenanceWindow
  pricingPlan: PER_USE
  replicationType: SYNCHRONOUS
  settingsVersion: '8'
  storageAutoResize: true
  storageAutoResizeLimit: '0'
  tier: db-f1-micro
state: RUNNABLE
```

Let me know if some other info would be useful for you. Thanks
