### ISSUE TITLE
Google Managed SSL Certificates

### ISSUE THREAD

**Issue by xskif** [pulumi/pulumi-gcp#572]
There is no way to create google-manged certs using gcp.compute.SSLCertificate

## Expected behavior

There are should be an option to provide a cert or create a new one using google managed SSL certs functionality.

## Current behavior

gcp.compute.SSLCertificate requires to provide SSL cert and private key files.

**Comment by xskif** [comment]
gcloud example:
```bash
gcloud compute ssl-certificates create example-name \
    --domains=api.example.com \
    --global
```

**Comment by xskif** [comment]
another example with GKE

```yml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: example-name
spec:
  domains:
    - api.example.com
```
