### ISSUE TITLE
gcp:dns/recordSet:RecordSet routingPolicy properties error

### ISSUE THREAD

**Issue by lctech-zeki** [pulumi/pulumi-gcp#830]
### What happened?

Use gcp dns [Geolocation](https://www.pulumi.com/registry/packages/gcp/api-docs/dns/recordset/#recordsetroutingpolicy) sample , but it not work

### Steps to reproduce

try this

```yaml
resources:
  geo:
    type: gcp:dns:RecordSet
    properties:
      name: backend.${google_dns_managed_zone.prod.dns_name}
      managedZone: ${google_dns_managed_zone.prod.name}
      type: A
      ttl: 300
      routingPolicy:
        geos:
          - location: asia-east1
            rrdatas:
              - 10.128.1.1
          - location: us-central1
            rrdatas:
              - 10.130.1.1
```

### Expected Behavior

add new record

### Actual Behavior

  pulumi:pulumi:Stack (domain-jkforum.one-prod):
    error: Property routingPolicy does not exist on Resource gcp:dns/recordSet:RecordSet
    
```
      on Pulumi.yaml line 51:
      51:       routingPolicy:
      52:         geos:
      53:           - location: asia-east1
      54:             rrdatas:
      55:               - 10.128.1.1
      56:           - location: us-central1
      57:             rrdatas:
      58:               - 10.130.1.1
   ```

Existing properties are: project, ttl, managedZone, name, rrdatas and 1 others
    error: an unhandled error occurred: failed to evaluate template

### Versions used

CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME  VERSION
gcp   unknown
yaml  unknown

Host     
OS       darwin
Version  12.3.1
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
