### ISSUE TITLE
SQL GCP deletionProtection does not work

### ISSUE THREAD

**Issue by bchanan03** [pulumi/pulumi-gcp#876]
### What happened?

I have used Pulumi SDK (Go) for provisioning SQL instance on GCP cloud. 
I have enabled deletionProtection as true. While protection works on Pulumi level - cannot destroy SQL instance using pulumi destroy - I am able to destroy SQL instance on GCP console as SQL is not protected.
Deleting the SQL from the console - break the Pulumi stake - you cannot update and recreate the SQL instance - complains resources already exists, cannot destroy state as resource was not found - leaving Pulumi stake broken.

When trying to destroy SQL using Pulumi - error:
```bash 
gcp:sql:DatabaseInstance (google-cloud-sql):
    error: deleting urn:pulumi:us-east4-dev-google-cloud-sql-example::google-cloud-sql-example::gcp:dummy/sql:Database$gcp:sql/databaseInstance:DatabaseInstance::google-cloud-sql: 1 error occurred:
    	* Error, failed to delete instance because deletion_protection is set to true. Set it to false to proceed with instance deletion
```

### Steps to reproduce

Provision any SQL instance (PostgresSQL - not sure if its related) and enable deletionProtection. Check the console - see SQL instance is not protected. 

See resource details where deletionProtection is enabled:

```yaml
+ gcp:sql/databaseInstance:DatabaseInstance: (create)
            [urn=urn:pulumi:us-east4-dev-google-cloud-sql-example::google-cloud-sql-example::gcp:myproject/sql:Database$gcp:sql/databaseInstance:DatabaseInstance::google-cloud-sql]
            databaseVersion   : "POSTGRES_12"
            deletionProtection: true
            name              : "google-cloud-sql-0b96b6d"
            project           : "my-project"
            region            : "us-east4"
            settings          : {
                availabilityType   : "REGIONAL"
                backupConfiguration: {
                    enabled                   : false
                    pointInTimeRecoveryEnabled: false
                }
                databaseFlags      : [
                    [0]: {
                        name      : "auto_explain.log_analyze"
                        value     : "on"
                    }
                    [1]: {
                        name      : "max_connections"
                        value     : "800"
                    }
                ]
                diskAutoresize     : true
                diskAutoresizeLimit: 0
                diskSize           : 200
                diskType           : "PD_SSD"
                insightsConfig     : {
                    queryInsightsEnabled: false
                    queryStringLength   : 1024
                }
                ipConfiguration    : {
                    ipv4Enabled   : false
                    privateNetwork: "projects/my-project/global/networks/dev-vpc"
                }
                pricingPlan        : "PER_USE"
                tier               : "db-custom-32-122880"
                userLabels         : {
                    compliance : "cisl1"
                    criticality: "2"
                    environment: "dev"
                    monitored  : "true"
                    name       : "myusername"
                    owner      : "devops_backend"
                    persistence: "persistent"
                    purpose    : "pulumi-common-google-cloud-sql-example"
                }
            }
```

### Actual Behavior

I am able to delete the SQL instance although provisioned as deletionProtection true

### Versions used

➜ google-cloud-sql-example pulumi version
v3.37.2

### Additional context

Issue also opened on Pulumi github: https://github.com/pulumi/pulumi/issues/10388

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
